spring.application.name=Apis-Currency
server.port=5000
# ? DB Aiven (MySQL)
spring.datasource.url=jdbc:mysql://mysql-178bb065-spring-angular-app.e.aivencloud.com:15366/weatherdb?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_Z4PCm0Y5WZFAu3cAGSE

# Railway REdis
spring.data.redis.url=redis://default:lGZOxJdQZZuXXCjUGMrnNgDQdApUEDnQ@tramway.proxy.rlwy.net:49800

# ? Pool
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

# ? Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ? JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect